Repository GSG-K3/ca-application-website, pull requests merged in 2020-05, with the labels that each got.

#68 Navbar component
  .gitignore
  .vscode/launch.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/App.test.js
  client/src/Components/About/index.js
  client/src/Components/About/style.js
  client/src/Components/Footer/index.js
  client/src/Components/Footer/style.js
  client/src/Components/MenuBar/index.js
  client/src/Components/MenuBar/style.js
  client/src/Components/NavBar/gsg_logo.png
  client/src/Components/NavBar/index.js
  client/src/Components/NavBar/style.js
  client/src/Components/NavBarProfile/girl.png
  client/src/Components/NavBarProfile/gsg_logo.png
  client/src/Components/NavBarProfile/index.js
  client/src/Components/NavBarProfile/style.js
  client/src/Components/Requierments/index.js
  client/src/Components/Requierments/style.js
  client/src/Components/SupportTeam/index.js
  client/src/Components/SupportTeam/style.js
  client/src/Components/TemporaryDrawer/index.js
  client/src/Components/TemporaryDrawer/style.js
  client/src/Components/TemporaryDrawerProfile/index.js
  client/src/Components/TemporaryDrawerProfile/style.js
  client/src/Screens/Contact/index.js
  client/src/Screens/Contact/style.js
  client/src/Screens/Home/index.js
  client/src/Screens/Login/index.js
  client/src/Screens/Login/style.js
  client/src/index.js
  client/src/theme.js
  package.json
  server/Screens/Home/index.js
  server/Screens/Home/style.js
  server/Screens/NotFoundPage/index.js
  server/controllers/index.js
Labels: Component, Done, Front-End, Home Page, T[2]d, Technical, changes-requested

#74 Footer section
  client/src/Components/Footer/index.js
  client/src/Components/Footer/style.js
  client/src/Components/ShareDialog/index.js
  client/src/Components/ShareDialog/style.js
  client/src/Screens/Home/index.js
Labels: Done, Front-End, Home Page, In-review, Technical, changes-requested

#96 this is the support team section
  client/src/App.js
  client/src/assets/Haneen.jpeg
  client/src/assets/discord.png
  client/src/assets/githubicon.png
  client/src/assets/slack.png
  client/src/components/CardsTeam/index.js
  client/src/components/CardsTeam/style.js
  client/src/components/SupportTeam/index.js
  client/src/components/SupportTeam/style.js
  server/database/sql/fake_data.sql
Labels: In-review

#97 frontend for the login page and solved some problems for the backend
  client/src/App.js
  client/src/assets/Polygon.png
  client/src/assets/loginpic.png
  client/src/components/LoginForm/index.js
  client/src/components/LoginForm/style.js
  client/src/screens/Login/index.js
  client/src/screens/Login/style.js
  server/database/sql/fake_data.sql
  server/helper/hashPassword.js
Labels: Done

#67 Success stories
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/Theme/MaterialUITheme.jsx
  client/src/assets/Haneen.jpeg
  client/src/assets/about.svg
  client/src/assets/quote-left.svg
  client/src/assets/success story Image.svg
  client/src/components/Stories/index.js
  client/src/components/Stories/style.js
  client/src/components/SuccessStories/index.jsx
  client/src/screens/Home/index.js
  package.json
  server/controllers/SuccessStories.js
  server/controllers/error.js
  server/controllers/index.js
  server/database/connection.js
  server/database/db_build.js
  server/database/fake_data.js
  server/database/queries/db_successStories.js
  server/database/sql/fake_data.sql
  server/helper/compareHashed.js
  server/helper/hashPassword.js
Labels: changes-requested

#95 Testing
  client/package.json
  client/public/index.html
  client/src/assets/EnglishRe.png
  client/src/assets/Fulltime.png
  client/src/assets/english.png
  client/src/assets/motivation.svg
  client/src/components/LoginForm/index.js
  client/src/components/Requierments/index.js
  client/src/components/Requierments/style.js
  client/src/components/Requirments/index.js
  client/src/components/Requirments/style.js
  client/src/img/logo.svg
  client/src/screens/Home/index.js
  client/src/screens/Login/index.js
  client/src/theme/materialUITheme.js
  server/database/sql/fake_data.sql
  server/helper/hashPassword.js
Labels: changes-requested
