Repository GSG-K3/ca-application-website, pull requests merged in 2020-06, with the labels that each got.

#138 modifying authentication-backEnd
  client/src/screens/Profile/index.js
  server/controllers/checkAuth.js
  server/controllers/index.js
  server/controllers/login.js
  server/database/connection.js
  server/middleware/auth.js
Labels: In-review, Refactor

#123 Personal profile
  client/package.json
  client/src/App.js
  client/src/components/AccountInfo/index.js
  client/src/components/ScoresInfo/index.js
  client/src/components/Tabs/index.js
  client/src/components/Tabs/style.js
  client/src/screens/Home/index.js
  client/src/screens/PersonalProfile/index.js
  client/src/screens/PersonalProfile/style.js
Labels: Done, In-review, Refactor

#124 Personal profile tabs
  client/src/components/AccountInfo/index.js
  client/src/components/Collapsible/index.js
  client/src/components/CollapsibleAccounts/index.js
  client/src/components/DropMenu/index.js
  client/src/components/LoginForm/index.js
  client/src/components/NavBar/index.js
  client/src/components/ProjectsTextfields/index.js
  client/src/components/ScoresInfo/index.js
  client/src/components/SuccessStories/index.jsx
  client/src/components/Tabs/TabPanel.js
  client/src/components/Tabs/a11yProps.js
  client/src/components/Tabs/index.js
  client/src/components/Textfields/index.js
  client/src/screens/Accounts/index.js
  client/src/screens/Home/index.js
  client/src/screens/PersonalInfo/index.js
  client/src/screens/PersonalProfile/contextProvider.js
  client/src/screens/PersonalProfile/index.js
  client/src/screens/Profile/index.js
  client/src/screens/Projects/index.js
  server/controllers/checkAuth.js
  server/controllers/error.js
  server/controllers/index.js
  server/controllers/login.js
  server/controllers/personalInfo.js
  server/controllers/profile.js
  server/controllers/projects.js
  server/database/queries/profile.js
  server/database/queries/projects.js
  server/middleware/auth.js
Labels: On Hold, Refactor, changes-requested

#137 Submit btn
  client/src/App.js
  client/src/assets/congrat.png
  client/src/screens/Profile/index.js
  client/src/screens/SubmitPage/index.js
  client/src/screens/SubmitPage/style.js
Labels: Done, Refactor, T[1]h
