Repository GSG-K3/ca-application-website, pull requests merged in 2020-04, with the labels that each got.

#41 setup the eslint and the prettier, connecting eslint with prettier #40
  .eslintrc.json
  .prettierrc
  client/.eslintrc.json
  client/.prettierrc
  client/package.json
  package.json
Labels: Approved

#44 Setup Server #43
  package.json
  server/app.js
  server/controllers/index.js
  server/database/dbBuild.js
  server/database/dbBuild.sql
  server/database/dbConnection.js
  server/index.js
Labels: Approved, Back-End, Technical

#63 Database
  .gitignore
  package.json
  server/database/connection.js
  server/database/dbBuild.js
  server/database/dbBuild.sql
  server/database/dbConnection.js
  server/database/db_build.js
  server/database/fake_data.js
  server/database/sql/db_build.sql
  server/database/sql/fake_data.sql
Labels: Back-End, In-review, Priority-1, T[4]h, Technical

#66 Connect client server
  client/package.json
  client/src/App.js
  client/src/Screens/Home/index.js
  client/src/Screens/Home/style.js
  client/src/Screens/NotFoundPage/index.js
  client/src/Screens/NotFoundPage/style.js
  client/src/index.js
  package.json
  server/app.js
  server/controllers/index.js
  server/database/connection.js
  server/index.js
Labels: Done
